#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xmodmap
Version  : 1.0.11
Release  : 6
URL      : https://www.x.org/releases/individual/app/xmodmap-1.0.11.tar.gz
Source0  : https://www.x.org/releases/individual/app/xmodmap-1.0.11.tar.gz
Source1  : https://www.x.org/releases/individual/app/xmodmap-1.0.11.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xmodmap-bin = %{version}-%{release}
Requires: xmodmap-license = %{version}-%{release}
Requires: xmodmap-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
The xmodmap program is used to edit and display the keyboard modifier
map and keymap table that are used by client applications to convert
event keycodes into keysyms.  It is usually run from the user's
session startup script to configure the keyboard according to personal
tastes.

%package bin
Summary: bin components for the xmodmap package.
Group: Binaries
Requires: xmodmap-license = %{version}-%{release}

%description bin
bin components for the xmodmap package.


%package license
Summary: license components for the xmodmap package.
Group: Default

%description license
license components for the xmodmap package.


%package man
Summary: man components for the xmodmap package.
Group: Default

%description man
man components for the xmodmap package.


%prep
%setup -q -n xmodmap-1.0.11
cd %{_builddir}/xmodmap-1.0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657508386
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1657508386
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xmodmap
cp %{_builddir}/xmodmap-1.0.11/COPYING %{buildroot}/usr/share/package-licenses/xmodmap/232975656d77e0826ea5a6329c5a44dd28525ecf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xmodmap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xmodmap/232975656d77e0826ea5a6329c5a44dd28525ecf

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xmodmap.1
